title: leexiyu's Blog
description: 前端开发者 · 记录技术与思考
author: leexiyu
email: leexiyu@outlook.com
url: "https://leexiyu.github.io"

markdown: kramdown
highlighter: rouge

permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "leexiyu"

feed:
  path: /feed.xml
